[package]
name = "promodj-scraper"
version = "2.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
eframe = "0.35"
egui = "0.35"
image = { version = "0.25", default-features = false, features = ["png", "ico"] }
rfd = "0.15"
configparser = "3.2"
chrono = "0.4"
strum = { version = "0.27", features = ["derive"] }

[build-dependencies]
embed-resource = "3"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
