[package]
name = "promodj-downloader"
version = "2.5.0"
edition = "2024"
build = "build.rs"

[dependencies]
eframe = "0.35"
egui = "0.35"
image = { version = "0.25", default-features = false, features = ["png", "ico"] }
rfd = "0.15"
configparser = "3.2"
chrono = "0.4"
strum = { version = "0.27", features = ["derive"] }
regex = "1.12"
tokio = { version =  "1.52", features = ["rt-multi-thread", "macros"] }
sqlx = { version = "0.9", features = [ "runtime-tokio", "tls-rustls", "sqlite" ] }
sqlx-core = "0.9"
reqwest = { version = "0.13", features = [ "stream", "http2" ] }
futures-util = "0.3"
anyhow = "1.0"
scraper = "0.27"
percent-encoding = "2.3"
aes-gcm = { version = "0.11", features = ["getrandom", "arrayvec", "rand_core"] }
rand = "0.10"

[dev-dependencies]
tempfile = "3"

[build-dependencies]
embed-resource = "3"

[features]
test = []

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
